import type { Metadata } from "next";
import { Rubik, Roboto_Mono } from "next/font/google";
import "./globals.css";
import NavBar from "../components/NavBar/NavBar";
import Menu from "../components/Menu/Menu";
import Banner from "../components/Banner/Banner";
import PopularReciepe from "../components/PopukarReciepe/PopularReciepe";
import Review from "../components/Review/Review";
import Footer from "../components/Footer/Footer";

const rubik = Rubik({
  variable: "--font-rubik",
  subsets: ["latin"],
});
const robotoMono = Roboto_Mono({
  variable: "--font-roboto-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Food App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${robotoMono.variable} h-full `}>
      <body className="min-h-full flex flex-col text-black overfloe-x-hidden bg-yellow-50">
        <div className="relative overflow-hidden">
          <NavBar></NavBar>
          {children}
        </div>
        <Menu></Menu>
        <Banner></Banner>
        <PopularReciepe></PopularReciepe>
        <div className="lg:h-20 lg:w-60 "></div>
        <Review></Review>
        <Footer></Footer>
      </body>
    </html>
  );
}
